from zsim.sim_progress.BuffGraph.blocks.registry import BlockPort, BuffGraphBlockDefinition
from zsim.sim_progress.BuffGraph.spec.schema import NodeFamily


CONDITION_BLOCKS = (
    BuffGraphBlockDefinition(
        block_id="condition.character_identity",
        family=NodeFamily.CONDITION,
        display_name="Character Identity",
        adapter_id="condition.character_identity.v1",
        input_ports=(BlockPort("context", "Context", "prepared_context"),),
        output_ports=(BlockPort("result", "Result", "bool"),),
        param_schema={"character": "character_selector"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.buff_active",
        family=NodeFamily.CONDITION,
        display_name="Buff Active",
        adapter_id="condition.buff_active.v1",
        input_ports=(BlockPort("context", "Context", "prepared_context"),),
        output_ports=(BlockPort("result", "Result", "bool"),),
        param_schema={"buff_index": "string"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.equipper_identity",
        family=NodeFamily.CONDITION,
        display_name="Equipper Identity",
        adapter_id="condition.equipper_identity.v1",
        input_ports=(BlockPort("equipper", "Equipper", "character"),),
        output_ports=(BlockPort("result", "Result", "bool"),),
        param_schema={"equipper": "character_selector"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.trigger_buff_active",
        family=NodeFamily.CONDITION,
        display_name="Trigger Buff Active",
        adapter_id="condition.trigger_buff_active.v1",
        input_ports=(BlockPort("trigger_buff_state", "Trigger Buff State", "buff_state"),),
        output_ports=(BlockPort("result", "Result", "bool"),),
        param_schema={"trigger_buff_index": "string"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.trigger_buff_box_size_equals",
        family=NodeFamily.CONDITION,
        display_name="Trigger Buff Box Size Equals",
        adapter_id="condition.trigger_buff_box_size_equals.v1",
        input_ports=(BlockPort("trigger_buff_state", "Trigger Buff State", "buff_state"),),
        output_ports=(BlockPort("result", "Result", "bool"),),
        param_schema={"expected_size": "number", "trigger_buff_index": "string"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.trigger_buff_count_compare",
        family=NodeFamily.CONDITION,
        display_name="Trigger Buff Count Compare",
        adapter_id="condition.trigger_buff_count_compare.v1",
        input_ports=(BlockPort("trigger_buff_state", "Trigger Buff State", "buff_state"),),
        output_ports=(BlockPort("result", "Result", "bool"),),
        param_schema={
            "expected_count": "number",
            "operator": "comparison_operator",
            "trigger_buff_index": "string",
        },
    ),
    BuffGraphBlockDefinition(
        block_id="condition.skill_trigger_level",
        family=NodeFamily.CONDITION,
        display_name="Skill Trigger Level",
        adapter_id="condition.skill_trigger_level.v1",
        input_ports=(BlockPort("context", "Context", "prepared_context"),),
        output_ports=(BlockPort("result", "Result", "bool"),),
        param_schema={"expected_level": "number", "operator": "comparison_operator"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.equipper_is_background",
        family=NodeFamily.CONDITION,
        display_name="Equipper Is Background",
        adapter_id="condition.equipper_is_background.v1",
        input_ports=(BlockPort("equipper", "Equipper", "character"),),
        output_ports=(BlockPort("result", "Result", "bool"),),
    ),
    BuffGraphBlockDefinition(
        block_id="condition.equipper_is_foreground",
        family=NodeFamily.CONDITION,
        display_name="Equipper Is Foreground",
        adapter_id="condition.equipper_is_foreground.v1",
        input_ports=(BlockPort("equipper", "Equipper", "character"),),
        output_ports=(BlockPort("result", "Result", "bool"),),
    ),
    BuffGraphBlockDefinition(
        block_id="condition.enemy_state",
        family=NodeFamily.CONDITION,
        display_name="Enemy State",
        adapter_id="condition.enemy_state.v1",
        input_ports=(BlockPort("anomaly_state", "Anomaly State", "enemy_anomaly_state"),),
        output_ports=(BlockPort("result", "Result", "bool"),),
        param_schema={"expected_state": "string", "active": "bool", "anomaly_key": "string"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.enemy_stun_active",
        family=NodeFamily.CONDITION,
        display_name="Enemy Stun Active",
        adapter_id="condition.enemy_stun_active.v1",
        input_ports=(BlockPort("enemy_stun_state", "Enemy Stun State", "enemy_stun_state"),),
        output_ports=(
            BlockPort("passed", "Passed", "bool"),
            BlockPort("active", "Active", "bool"),
        ),
        param_schema={"active": "bool"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.edge_transition",
        family=NodeFamily.CONDITION,
        display_name="Edge Transition",
        adapter_id="condition.edge_transition.v1",
        input_ports=(BlockPort("edge_state", "Edge State", "edge_state"),),
        output_ports=(BlockPort("result", "Result", "bool"),),
        param_schema={"transition": "edge_transition", "from_state": "any", "to_state": "any"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.tick_window",
        family=NodeFamily.CONDITION,
        display_name="Tick Window",
        adapter_id="condition.tick_window.v1",
        input_ports=(BlockPort("tick", "Tick", "tick"),),
        output_ports=(
            BlockPort("result", "Result", "bool"),
            BlockPort("tick", "Tick", "tick"),
        ),
        param_schema={"start_tick": "int", "end_tick": "int"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.hit_frame",
        family=NodeFamily.CONDITION,
        display_name="Hit Frame",
        adapter_id="condition.hit_frame.v1",
        input_ports=(BlockPort("skill_node", "Skill Node", "skill_node"),),
        output_ports=(
            BlockPort("result", "Result", "bool"),
            BlockPort("hit_index", "Hit Index", "number"),
            BlockPort("is_last_hit", "Is Last Hit", "bool"),
        ),
        param_schema={"expected_hit_index": "int", "require_last_hit": "bool"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.skill_tag_in",
        family=NodeFamily.CONDITION,
        display_name="Skill Tag In",
        adapter_id="condition.skill_tag_in.v1",
        input_ports=(BlockPort("skill_node", "Skill Node", "skill_node"),),
        output_ports=(
            BlockPort("result", "Result", "bool"),
            BlockPort("skill_tag", "Skill Tag", "string"),
        ),
        param_schema={"skill_tags": "string_list"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.skill_owner_not_self",
        family=NodeFamily.CONDITION,
        display_name="Skill Owner Not Self",
        adapter_id="condition.skill_owner_not_self.v1",
        input_ports=(BlockPort("skill_node", "Skill Node", "skill_node"),),
        output_ports=(
            BlockPort("result", "Result", "bool"),
            BlockPort("skill_owner", "Skill Owner", "character"),
        ),
        param_schema={"self_owner": "character_selector"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.operating_character",
        family=NodeFamily.CONDITION,
        display_name="Operating Character",
        adapter_id="condition.operating_character.v1",
        input_ports=(BlockPort("character", "Character", "character"),),
        output_ports=(BlockPort("result", "Result", "bool"),),
        param_schema={"character": "character_selector"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.skill_owner",
        family=NodeFamily.CONDITION,
        display_name="Skill Owner",
        adapter_id="condition.skill_owner.v1",
        input_ports=(BlockPort("skill_node", "Skill Node", "skill_node"),),
        output_ports=(
            BlockPort("result", "Result", "bool"),
            BlockPort("skill_owner", "Skill Owner", "character"),
        ),
        param_schema={"owner": "character_selector"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.character_state",
        family=NodeFamily.CONDITION,
        display_name="Character State",
        adapter_id="condition.character_state.v1",
        input_ports=(BlockPort("character", "Character", "character"),),
        output_ports=(
            BlockPort("result", "Result", "bool"),
            BlockPort("state_value", "State Value", "any"),
        ),
        param_schema={"state_key": "string", "expected_value": "any", "character": "character_selector"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.cooldown_ready",
        family=NodeFamily.CONDITION,
        display_name="Cooldown Ready",
        adapter_id="condition.cooldown_ready.v1",
        input_ports=(BlockPort("tick", "Tick", "tick"),),
        output_ports=(BlockPort("result", "Result", "bool"),),
        param_schema={
            "cooldown_key": "string",
            "cooldown_ticks": "int",
            "operator": "comparison_operator",
        },
    ),
    BuffGraphBlockDefinition(
        block_id="condition.preload_tick",
        family=NodeFamily.CONDITION,
        display_name="Preload Tick",
        adapter_id="condition.preload_tick.v1",
        input_ports=(BlockPort("tick", "Tick", "tick"),),
        output_ports=(BlockPort("result", "Result", "bool"),),
        param_schema={"expected_tick": "int", "window_ticks": "int"},
    ),
    BuffGraphBlockDefinition(
        block_id="condition.numeric_compare",
        family=NodeFamily.CONDITION,
        display_name="Numeric Compare",
        adapter_id="condition.numeric_compare.v1",
        input_ports=(BlockPort("value", "Value", "number"),),
        output_ports=(
            BlockPort("passed", "Passed", "bool"),
            BlockPort("actual", "Actual", "number"),
            BlockPort("expected", "Expected", "number"),
        ),
        param_schema={"operator": "comparison_operator", "expected": "number"},
    ),
)

