from zsim.sim_progress.BuffGraph.blocks.registry import BlockPort, BuffGraphBlockDefinition
from zsim.sim_progress.BuffGraph.spec.schema import NodeFamily


EFFECT_BLOCKS = (
    BuffGraphBlockDefinition(
        block_id="effect.start_buff",
        family=NodeFamily.EFFECT,
        display_name="Start Buff",
        adapter_id="effect.start_buff.v1",
        input_ports=(
            BlockPort("condition", "Condition", "bool"),
            BlockPort("context", "Context", "prepared_context"),
        ),
        output_ports=(BlockPort("result", "Result", "effect_result"),),
        param_schema={"target_buff_index": "string"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.update_buff_count",
        family=NodeFamily.EFFECT,
        display_name="Update Buff Count",
        adapter_id="effect.update_buff_count.v1",
        input_ports=(BlockPort("value", "Value", "number"),),
        output_ports=(BlockPort("result", "Result", "effect_result"),),
        param_schema={"target_buff_index": "string", "mode": "set_or_add"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.update_template_buff",
        family=NodeFamily.EFFECT,
        display_name="Update Template Buff",
        adapter_id="effect.update_template_buff.v1",
        input_ports=(
            BlockPort("template_buff", "Template Buff", "buff_template"),
            BlockPort("condition", "Condition", "bool"),
        ),
        output_ports=(BlockPort("result", "Result", "effect_result"),),
        param_schema={"template_buff_index": "string", "mode": "set_or_add"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.bind_prepared_record",
        family=NodeFamily.EFFECT,
        display_name="Bind Prepared Record",
        adapter_id="effect.bind_prepared_record.v1",
        input_ports=(BlockPort("context", "Context", "prepared_context"),),
        output_ports=(BlockPort("binding", "Binding", "prepared_record_binding"),),
        param_schema={"record_key": "string"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.register_listener",
        family=NodeFamily.EFFECT,
        display_name="Register Listener",
        adapter_id="effect.register_listener.v1",
        input_ports=(BlockPort("context", "Context", "prepared_context"),),
        output_ports=(BlockPort("listener_registration", "Listener Registration", "effect_result"),),
        param_schema={"listener_key": "string", "source_buff_index": "string"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.consume_listener_signal",
        family=NodeFamily.EFFECT,
        display_name="Consume Listener Signal",
        adapter_id="effect.consume_listener_signal.v1",
        input_ports=(BlockPort("listener_signal", "Listener Signal", "listener_signal"),),
        output_ports=(BlockPort("listener_consumption", "Listener Consumption", "effect_result"),),
        param_schema={"listener_key": "string", "consume": "bool"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.issue_runtime_command",
        family=NodeFamily.EFFECT,
        display_name="Issue Runtime Command Intent",
        adapter_id="effect.issue_runtime_command.v1",
        input_ports=(BlockPort("condition", "Condition", "bool"),),
        output_ports=(BlockPort("runtime_command_intent", "Runtime Command Intent", "intent"),),
        param_schema={"command_type": "string", "command_name": "string", "payload": "object"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.issue_allowed_runtime_command",
        family=NodeFamily.EFFECT,
        display_name="Issue Allowed Runtime Command Intent",
        adapter_id="effect.issue_allowed_runtime_command.v1",
        input_ports=(BlockPort("condition", "Condition", "bool"),),
        output_ports=(BlockPort("runtime_command_intent", "Runtime Command Intent", "intent"),),
        param_schema={"command_type": "string", "command_name": "string", "payload": "object"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.emit_scheduled_event",
        family=NodeFamily.EFFECT,
        display_name="Emit Scheduled Event Intent",
        adapter_id="effect.emit_scheduled_event.v1",
        input_ports=(BlockPort("condition", "Condition", "bool"),),
        output_ports=(BlockPort("scheduled_event_intent", "Scheduled Event Intent", "intent"),),
        param_schema={"event_type": "string", "scheduled_tick": "int", "payload": "object"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.update_character_manager",
        family=NodeFamily.EFFECT,
        display_name="Update Character Manager Intent",
        adapter_id="effect.update_character_manager.v1",
        input_ports=(BlockPort("condition", "Condition", "bool"),),
        output_ports=(BlockPort("character_side_effect_intent", "Character Side Effect Intent", "intent"),),
        param_schema={"manager": "string", "operation": "string", "payload": "object"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.force_quick_assist",
        family=NodeFamily.EFFECT,
        display_name="Force Quick Assist Intent",
        adapter_id="effect.force_quick_assist.v1",
        input_ports=(BlockPort("condition", "Condition", "bool"),),
        output_ports=(BlockPort("character_side_effect_intent", "Character Side Effect Intent", "intent"),),
        param_schema={"target": "character_selector", "payload": "object"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.set_skill_node_force_qte_trigger",
        family=NodeFamily.EFFECT,
        display_name="Set Skill Node Force QTE Trigger Intent",
        adapter_id="effect.set_skill_node_force_qte_trigger.v1",
        input_ports=(BlockPort("pending_skill_node_signal", "Pending Skill Node Signal", "pending_skill_node_signal"),),
        output_ports=(BlockPort("skill_node_mutation_intent", "Skill Node Mutation Intent", "intent"),),
        param_schema={"value": "bool", "payload": "object"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.notify_schedule_process_state",
        family=NodeFamily.EFFECT,
        display_name="Notify Schedule Process State Intent",
        adapter_id="effect.notify_schedule_process_state.v1",
        input_ports=(BlockPort("condition", "Condition", "bool"),),
        output_ports=(BlockPort("process_state_notification_intent", "Process State Notification Intent", "intent"),),
        param_schema={"reason": "string", "report_flag": "string", "payload": "object"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.spawn_coattack",
        family=NodeFamily.EFFECT,
        display_name="Spawn Coattack Intent",
        adapter_id="effect.spawn_coattack.v1",
        input_ports=(BlockPort("condition", "Condition", "bool"),),
        output_ports=(BlockPort("character_side_effect_intent", "Character Side Effect Intent", "intent"),),
        param_schema={"skill_tag": "string", "target": "character_selector", "payload": "object"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.spawn_extra_attack",
        family=NodeFamily.EFFECT,
        display_name="Spawn Extra Attack Intent",
        adapter_id="effect.spawn_extra_attack.v1",
        input_ports=(BlockPort("condition", "Condition", "bool"),),
        output_ports=(BlockPort("character_side_effect_intent", "Character Side Effect Intent", "intent"),),
        param_schema={"skill_tag": "string", "target": "character_selector", "payload": "object"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.spawn_planned_skill_node",
        family=NodeFamily.EFFECT,
        display_name="Spawn Planned Skill Node Intent",
        adapter_id="effect.spawn_planned_skill_node.v1",
        input_ports=(BlockPort("condition", "Condition", "bool"),),
        output_ports=(BlockPort("character_side_effect_intent", "Character Side Effect Intent", "intent"),),
        param_schema={"skill_tag": "string", "scheduled_tick": "int", "payload": "object"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.update_character_resource",
        family=NodeFamily.EFFECT,
        display_name="Update Character Resource Intent",
        adapter_id="effect.update_character_resource.v1",
        input_ports=(BlockPort("condition", "Condition", "bool"),),
        output_ports=(BlockPort("character_side_effect_intent", "Character Side Effect Intent", "intent"),),
        param_schema={"resource": "string", "mode": "set_or_add", "payload": "object"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.external_add_skill",
        family=NodeFamily.EFFECT,
        display_name="External Add Skill Intent",
        adapter_id="effect.external_add_skill.v1",
        input_ports=(BlockPort("condition", "Condition", "bool"),),
        output_ports=(BlockPort("character_side_effect_intent", "Character Side Effect Intent", "intent"),),
        param_schema={"skill_tag": "string", "payload": "object"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.spawn_anomaly_output",
        family=NodeFamily.EFFECT,
        display_name="Spawn Anomaly Output Intent",
        adapter_id="effect.spawn_anomaly_output.v1",
        input_ports=(BlockPort("condition", "Condition", "bool"),),
        output_ports=(BlockPort("anomaly_output_intent", "Anomaly Output Intent", "intent"),),
        param_schema={"anomaly_key": "string", "output_type": "string", "payload": "object"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.start_dot",
        family=NodeFamily.EFFECT,
        display_name="Start DOT Intent",
        adapter_id="effect.start_dot.v1",
        input_ports=(BlockPort("condition", "Condition", "bool"),),
        output_ports=(BlockPort("dot_runtime_intent", "DOT Runtime Intent", "intent"),),
        param_schema={"dot_key": "string", "duration_ticks": "int", "payload": "object"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.register_dot_runtime",
        family=NodeFamily.EFFECT,
        display_name="Register DOT Runtime Intent",
        adapter_id="effect.register_dot_runtime.v1",
        input_ports=(BlockPort("condition", "Condition", "bool"),),
        output_ports=(BlockPort("dot_runtime_intent", "DOT Runtime Intent", "intent"),),
        param_schema={"dot_key": "string", "owner": "character_selector", "payload": "object"},
    ),
    BuffGraphBlockDefinition(
        block_id="effect.publish_resource_refresh",
        family=NodeFamily.EFFECT,
        display_name="Publish Resource Refresh Intent",
        adapter_id="effect.publish_resource_refresh.v1",
        input_ports=(BlockPort("condition", "Condition", "bool"),),
        output_ports=(BlockPort("resource_refresh_intent", "Resource Refresh Intent", "intent"),),
        param_schema={"resource": "string", "amount": "number", "payload": "object"},
    ),
)

