from zsim.sim_progress.BuffGraph.blocks.registry import BlockPort, BuffGraphBlockDefinition
from zsim.sim_progress.BuffGraph.spec.schema import NodeFamily


READ_BLOCKS = (
    BuffGraphBlockDefinition(
        block_id="read.current_tick",
        family=NodeFamily.READ,
        display_name="Current Tick",
        adapter_id="read.current_tick.v1",
        input_ports=(),
        output_ports=(BlockPort("tick", "Tick", "tick"),),
    ),
    BuffGraphBlockDefinition(
        block_id="read.buff_runtime_view",
        family=NodeFamily.READ,
        display_name="Buff Runtime View",
        adapter_id="read.buff_runtime_view.v1",
        input_ports=(BlockPort("context", "Context", "prepared_context"),),
        output_ports=(BlockPort("value", "Value", "buff_state"),),
        param_schema={"field": "buff_runtime_field"},
    ),
    BuffGraphBlockDefinition(
        block_id="read.prepared_owner",
        family=NodeFamily.READ,
        display_name="Prepared Owner",
        adapter_id="read.prepared_owner.v1",
        input_ports=(BlockPort("context", "Context", "prepared_context"),),
        output_ports=(BlockPort("owner", "Owner", "character"),),
    ),
    BuffGraphBlockDefinition(
        block_id="read.prepared_equipper",
        family=NodeFamily.READ,
        display_name="Prepared Equipper",
        adapter_id="read.prepared_equipper.v1",
        input_ports=(BlockPort("context", "Context", "prepared_context"),),
        output_ports=(BlockPort("equipper", "Equipper", "character"),),
    ),
    BuffGraphBlockDefinition(
        block_id="read.prepared_template_buff",
        family=NodeFamily.READ,
        display_name="Prepared Template Buff",
        adapter_id="read.prepared_template_buff.v1",
        input_ports=(BlockPort("context", "Context", "prepared_context"),),
        output_ports=(BlockPort("template_buff", "Template Buff", "buff_template"),),
        param_schema={"template_buff_index": "string"},
    ),
    BuffGraphBlockDefinition(
        block_id="read.trigger_buff_state",
        family=NodeFamily.READ,
        display_name="Trigger Buff State",
        adapter_id="read.trigger_buff_state.v1",
        input_ports=(BlockPort("context", "Context", "prepared_context"),),
        output_ports=(
            BlockPort("trigger_buff_state", "Trigger Buff State", "buff_state"),
            BlockPort("active", "Active", "bool"),
            BlockPort("count", "Count", "number"),
            BlockPort("built_in_buff_box_size", "Built-In Buff Box Size", "number"),
        ),
        param_schema={"trigger_buff_index": "string"},
    ),
    BuffGraphBlockDefinition(
        block_id="read.foreground_character",
        family=NodeFamily.READ,
        display_name="Foreground Character",
        adapter_id="read.foreground_character.v1",
        input_ports=(BlockPort("context", "Context", "prepared_context"),),
        output_ports=(BlockPort("character", "Character", "character"),),
    ),
    BuffGraphBlockDefinition(
        block_id="read.active_buffs_for_equipper",
        family=NodeFamily.READ,
        display_name="Active Buffs For Equipper",
        adapter_id="read.active_buffs_for_equipper.v1",
        input_ports=(
            BlockPort("context", "Context", "prepared_context"),
            BlockPort("equipper", "Equipper", "character"),
        ),
        output_ports=(
            BlockPort("active_buffs", "Active Buffs", "buff_list"),
            BlockPort("active_buff_count", "Active Buff Count", "number"),
            BlockPort("equipper", "Equipper", "character"),
        ),
    ),
    BuffGraphBlockDefinition(
        block_id="read.listener_signal",
        family=NodeFamily.READ,
        display_name="Listener Signal",
        adapter_id="read.listener_signal.v1",
        input_ports=(BlockPort("context", "Context", "prepared_context"),),
        output_ports=(
            BlockPort("listener_signal", "Listener Signal", "listener_signal"),
            BlockPort("matched", "Matched", "bool"),
            BlockPort("listener_key", "Listener Key", "string"),
        ),
        param_schema={"listener_key": "string", "signal_key": "string"},
    ),
    BuffGraphBlockDefinition(
        block_id="read.enemy_context",
        family=NodeFamily.READ,
        display_name="Enemy Context",
        adapter_id="read.enemy_context.v1",
        input_ports=(BlockPort("context", "Context", "prepared_context"),),
        output_ports=(BlockPort("enemy_context", "Enemy Context", "enemy_context"),),
    ),
    BuffGraphBlockDefinition(
        block_id="read.enemy_anomaly_state",
        family=NodeFamily.READ,
        display_name="Enemy Anomaly State",
        adapter_id="read.enemy_anomaly_state.v1",
        input_ports=(BlockPort("enemy_context", "Enemy Context", "enemy_context"),),
        output_ports=(
            BlockPort("anomaly_state", "Anomaly State", "enemy_anomaly_state"),
            BlockPort("state_value", "State Value", "string"),
            BlockPort("active", "Active", "bool"),
            BlockPort("anomaly_key", "Anomaly Key", "string"),
        ),
        param_schema={"anomaly_key": "string", "element": "string"},
    ),
    BuffGraphBlockDefinition(
        block_id="read.enemy_anomaly_bar",
        family=NodeFamily.READ,
        display_name="Enemy Anomaly Bar",
        adapter_id="read.enemy_anomaly_bar.v1",
        input_ports=(BlockPort("enemy_context", "Enemy Context", "enemy_context"),),
        output_ports=(
            BlockPort("anomaly_bar", "Anomaly Bar", "enemy_anomaly_bar"),
            BlockPort("anomaly_value", "Anomaly Value", "number"),
            BlockPort("anomaly_threshold", "Anomaly Threshold", "number"),
            BlockPort("anomaly_ratio", "Anomaly Ratio", "number"),
        ),
        param_schema={"anomaly_key": "string", "element": "string"},
    ),
    BuffGraphBlockDefinition(
        block_id="read.enemy_edge_state",
        family=NodeFamily.READ,
        display_name="Enemy Edge State",
        adapter_id="read.enemy_edge_state.v1",
        input_ports=(BlockPort("context", "Context", "prepared_context"),),
        output_ports=(
            BlockPort("edge_state", "Edge State", "edge_state"),
            BlockPort("previous", "Previous", "any"),
            BlockPort("current", "Current", "any"),
            BlockPort("changed", "Changed", "bool"),
        ),
        param_schema={"edge_key": "string", "state_key": "string"},
    ),
    BuffGraphBlockDefinition(
        block_id="read.dot_runtime_state",
        family=NodeFamily.READ,
        display_name="DOT Runtime State",
        adapter_id="read.dot_runtime_state.v1",
        input_ports=(BlockPort("context", "Context", "prepared_context"),),
        output_ports=(
            BlockPort("dot_runtime_state", "DOT Runtime State", "dot_runtime_state"),
            BlockPort("active", "Active", "bool"),
            BlockPort("dot_key", "DOT Key", "string"),
        ),
        param_schema={"dot_key": "string"},
    ),
)

